apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xfwii4wtw-python
  janus-idp.io/tekton: xfwii4wtw-python
  backstage.io/kubernetes-id: xfwii4wtw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xfwii4wtw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
